import { useAnimations, useGLTF } from '@react-three/drei'
import { useEffect, useRef } from 'react'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
export function Korrigan(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/korrigan-hat/model.gltf')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.course_chapeau.play()
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, 0.01, 0]} scale={2}>
        <primitive object={nodes.root} />
        <skinnedMesh geometry={nodes.Chapeau.geometry} material={materials['color_main.014']} skeleton={nodes.Chapeau.skeleton} />
      </group>
    </group>
  )
}
useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/korrigan-hat/model.gltf')
