/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { a, easings, useSpring } from '@react-spring/three'

export default function Tree(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/tree-spruce/model.gltf')

  const [{ scaleY }, treeAPI] = useSpring(() => ({
    from: { scaleY: 0 },
    config: { duration: 250, easing: easings.easeOutQuad }
  }))

  useEffect(() => {
    treeAPI.start({ to: { scaleY: 1 } })
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <a.group scale-y={scaleY}>
        <mesh geometry={nodes['tree-spruce'].geometry} material={materials.color_main} />
      </a.group>
    </group>
  )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/tree-spruce/model.gltf')
